easy_admin:
    design:
        brand_color: '#0A7840'

        menu:
         - {entity: 'Cart', label: 'Paniers clients', icon: 'shopping-cart'}
         - {entity: 'Product', label: 'listes des images', icon: 'file-image-o'}
         - {entity: 'SupportImages', label: 'Supports des images', icon: 'paint-brush'}
         - {entity: 'DimensionImages', label: 'Dimensions des images', icon: 'image'}
         - {entity: 'Configuration', label: 'Configuration du serveur', icon: 'tag'}

    site_name: '<em style="font-size: 80%;">Administration</em>'

    entities:
        # List the entity class name you want to manage
        Cart:
            class: App\Entity\Cart
        Product:
            class: App\Entity\Product
        SupportImages:
            class: App\Entity\SupportImage
        DimensionImages:
            class: App\Entity\DimensionFormatImage
        Configuration:
            class: App\Entity\Configuration
