vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /api/image/upload
            upload_destination: '%kernel.project_dir%/public/images/products'
#            namer: vich_uploader.namer_uniqid
            namer: vich_uploader.namer_origname

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true